package com.skylands.skylands;

import net.neoforged.neoforge.common.ModConfigSpec;

public final class SkylandsConfig {
    private static final ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();

    // 关于如何定义biome
    //  在配置文件中写入一种空岛
    //  包含
    //  地表方块（表层，可以为空，为空会被地下方块代替）
    //  地表副方块（点缀，可以为空）
    //  地下方块（表层下填充）
    //  地下副方块（点缀，类似原版的闪长岩，可以为空）
    //  是否启用深层（是否启用深层方块，默认否）
    //  深层启用线（比例，下而上，比如0.7代表下部分70%为深层，默认0.5）
    //  深层方块（深层，默认深板岩，即使不启用深层也可以填，只是不生成）
    //  深层副方块（点缀，类似原版凝灰岩，可以为空）
    //  矿石列表（可生成矿物，不填默认全选）
    //  悬挂方块（悬挂在洞穴顶部与岛屿尖锥上，可以为空）
    //  生成要求（噪声要求，必须全填不然不生成，例如湿度>0.5、温度>0.5等）
    //  生成优先度（决定在多个满足的群系中生成哪个）
    //  生成概率（目前没用，默认1，效果为生成成功的概率）
    //  地形（决定地形起伏等）
    //  结构列表（决定可生成结构）
    //  与模组联动内容（先不急，但是留个位置）

    public static final ModConfigSpec.IntValue MIN_RADIUS =
            BUILDER.comment(
                    "关于如何定义biome",
                    " 在配置文件中写入一种空岛",
                    " 包含",
                    " 地表方块（表层，可以为空，为空会被地下方块代替）",
                    " 地表副方块（点缀，可以为空）",
                    " 地下方块（表层下填充）",
                    " 地下副方块（点缀，类似原版的闪长岩，可以为空）",
                    " 是否启用深层（是否启用深层方块，默认否）",
                    " 深层启用线（比例，下而上，比如0.7代表下部分70%为深层，默认0.5）",
                    " 深层方块（深层，默认深板岩，即使不启用深层也可以填，只是不生成）",
                    " 深层副方块（点缀，类似原版凝灰岩，可以为空）",
                    " 矿石列表（可生成矿物，不填默认全选）",
                    " 悬挂方块（悬挂在洞穴顶部与岛屿尖锥上，可以为空）",
                    " 生成要求（噪声要求，必须全填不然不生成，例如湿度>0.5、温度>0.5等）",
                    " 生成优先度（决定在多个满足的群系中生成哪个）",
                    " 生成概率（目前没用，默认1，效果为生成成功的概率）",
                    " 地形（决定地形起伏等）",
                    " 结构列表（决定可生成结构）",
                    " 与模组联动内容（先不急，但是留个位置）"
            ).defineInRange("islands.minRadius", 128, 50, 100000);
    public static final ModConfigSpec.IntValue MAX_RADIUS =
            BUILDER.defineInRange("islands.maxRadius", 180, 50, 100000);
    public static final ModConfigSpec.IntValue SPACING =
            BUILDER.defineInRange("islands.spacing", 600, 128, 100000);
    public static final ModConfigSpec.IntValue CENTER_Y =
            BUILDER.defineInRange("islands.centerY", 100, -64, 320);
    public static final ModConfigSpec.IntValue HEIGHT_JITTER =
            BUILDER.defineInRange("islands.heightJitter", 32, 0, 256);
    public static final ModConfigSpec.IntValue MIN_TARGET_Y =
            BUILDER.defineInRange("islands.minTargetY", 20, -64, 320);
    public static final ModConfigSpec.IntValue MAX_TARGET_Y =
            BUILDER.defineInRange("islands.maxTargetY", 120, -64, 320);
    public static final ModConfigSpec.IntValue SURFACE_ANCHOR_MAX_RISE =
            BUILDER.defineInRange("islands.surfaceAnchorMaxRise", 50, 0, 256);
    public static final ModConfigSpec.IntValue SURFACE_ANCHOR_MAX_DROP =
            BUILDER.defineInRange("islands.surfaceAnchorMaxDrop", 40, 0, 256);
    public static final ModConfigSpec.IntValue SURFACE_SHELL_DEPTH =
            BUILDER.defineInRange("islands.surfaceShellDepth", 6, 1, 32);
    public static final ModConfigSpec.DoubleValue VERTICAL_SCALE =
            BUILDER.defineInRange("islands.verticalScale", 0.35D, 0.05D, 5.0D);
    public static final ModConfigSpec.DoubleValue EDGE_NOISE =
            BUILDER.defineInRange("islands.edgeNoise", 24.0D, 0.0D, 512.0D);
    public static final ModConfigSpec.BooleanValue ENABLE_OCEAN_ISLANDS =
            BUILDER.define("islands.enableOceanIslands", false);

    public static final ModConfigSpec.BooleanValue ISLAND_BIOME_OVERRIDE_ENABLED =
            BUILDER.define("islandBiomes.overrideEnabled", true);
    public static final ModConfigSpec.IntValue ISLAND_BIOME_MARGIN =
            BUILDER.defineInRange("islandBiomes.margin", 50, 0, 64);
    public static final ModConfigSpec.ConfigValue<String> ISLAND_BIOME_DEFINITION_FORMAT =
            BUILDER.comment(
                    "Biome entry format:",
                    "surfaceDetail modes:",
                    "- empty or <block_id>: legacy surface patch (top block only)",
                    "- 随机替换[blocks,(target),ratio,patchSize]: top-only patch; patchSize=1 becomes per-block random",
                    "- 团块[blocks,(target),volume,ratio]: blob across surface shell depth",
                    "- bulb[block,volume,ratio] or 巨石[block,volume,ratio]: ground boulder sitting on the surface",
                    "- 表层[block,volume,(ratio)]: top-only patch (large plates); ignores steep side exposure",
                    "biome=<biome_id>;" +
                            "surface=<block_id_or_empty>;" +
                            "surfaceDetail=<block_id_or_empty>;" +
                            "surfaceLayers=<empty or [block_id,count;block_id,count;...]>;" +
                            "subsurface=<block_id_or_empty (default stone)>;" +
                            "subsurfaceDetail=<block_id_or_empty>;" +
                            "badlandsDetail=<empty or near_surface_block,min-max,split_line,[band_block;band_block;...] >;" +
                            "deepEnabled=<true_or_false>;" +
                            "deepLayerLinie=<0..1>;" +
                            "deep=<block_d>;" +
                            "deepDetail=<empty or block_id or [block_id,volume,ratio;block_id,volume,ratio;...]>;" +
                            "ores=<* or comma separated ore ids; ore_id=generic source, ore_id@placed_feature_id=specific special source, ore_id@biome_id=all special sources referenced by that biome>;" +
                            "liquidPools=<empty or [[liquid_id,density,shape,size,depth,[bottom1;bottom2;...]];[definition2;...]]>;" +
                            "features=<empty or block_id,density,probability,required_bottom;...>;" +
                            "hanging=<block_id_or_empty>;" +
                            "requirements=temperature>value,humidity>value,continentalness>value,erosion<value,weirdness>value,depth>value;" +
                            "priority=<int>;" +
                            "probability=<0..1>;" +
                            "terrain=<name: 平坦/起伏/山丘/多山/高峰/平顶山/火山 or flat/rolling/hills/mountains/peaks/mesa/volcano>;" +
                            "structures=<comma separated ids or empty>;" +
                            "modded=<comma separated placeholders or empty>"
            ).define("islandBiomes.definitionFormat", "");
    public static final ModConfigSpec.ConfigValue<java.util.List<? extends String>> ISLAND_BIOME_DEFINITIONS =
            BUILDER.defineListAllowEmpty(
                    "islandBiomes.definitions",
                    java.util.List.of(
                            "biome=minecraft:ice_spikes;surface=minecraft:snow_block;surfaceDetail=表层[minecraft:ice,6,0.35];surfaceLayers=团块[minecraft:packed_ice,minecraft:stone,5,0.15];subsurface=minecraft:stone;subsurfaceDetail=minecraft:granite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=minecraft:ice,0.03,0.25,minecraft:snow_block,0,0,1#minecraft:packed_ice,0.01,0.1,minecraft:snow_block,0,0,1;underhang=;hanging=;requirements=temperature<=-0.35;priority=300;probability=1.00;terrain=peaks;structures=;modded=",
                            "biome=minecraft:eroded_badlands;surface=minecraft:red_sand;surfaceDetail=表层[minecraft:terracotta,5,0.60];surfaceLayers=团块[minecraft:red_sand,minecraft:stone,3,0.12];subsurface=minecraft:stone;subsurfaceDetail=minecraft:terracotta;badlandsDetail=minecraft:terracotta,64,0.58,[minecraft:orange_terracotta;minecraft:yellow_terracotta;minecraft:white_terracotta;minecraft:light_gray_terracotta;minecraft:brown_terracotta;minecraft:red_terracotta];deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:granite;ores=default;liquidPools=;features=minecraft:dead_bush,0.08,0.4,minecraft:red_sand,0,0,1;underhang=underhang(vine,2,10,12,vine,[minecraft:sandstone|minecraft:smooth_sandstone|minecraft:stone]);hanging=;requirements=temperature>=0.20,humidity<=-0.10,erosion>=0.25,weirdness<=-0.10;priority=220;probability=1.00;terrain=peaks;structures=;modded=",
                            "biome=minecraft:cherry_grove;surface=minecraft:grass_block;surfaceDetail=随机替换[minecraft:grass_block|minecraft:pink_petals|minecraft:moss_block,minecraft:stone,0.55,1500];surfaceLayers=团块[minecraft:pink_petals,minecraft:grass_block,1,0.30];subsurface=minecraft:stone;subsurfaceDetail=minecraft:diorite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=@minecraft:cherry_checked,0.15,0.65,minecraft:grass_block,7,9,2#minecraft:pink_petals,0.25,0.65,minecraft:grass_block,0,0,1#minecraft:short_grass,0.18,0.55,minecraft:grass_block,0,0,1;underhang=underhang(cave_vines_plant,2,12,24,cave_vines,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|create:limestone],minecraft:moss_block);hanging=;requirements=temperature=-0.05..0.30,humidity=0.05..0.40,weirdness<=-0.15;priority=212;probability=1.00;terrain=hills;structures=;modded=",
                            "biome=minecraft:bamboo_jungle;surface=minecraft:grass_block;surfaceDetail=随机替换[minecraft:grass_block|minecraft:podzol|minecraft:moss_block,minecraft:stone,0.60,1800];surfaceLayers=团块[minecraft:podzol,minecraft:stone,4,0.30];subsurface=minecraft:stone;subsurfaceDetail=minecraft:granite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=minecraft:bamboo,0.42,0.90,minecraft:grass_block|minecraft:podzol,8,0,1#@minecraft:jungle_tree_checked,0.14,0.6,minecraft:grass_block|minecraft:podzol,9,11,1#@minecraft:fancy_oak_checked,0.07,0.45,minecraft:grass_block|minecraft:podzol,9,10,1#minecraft:large_fern,0.18,0.65,minecraft:grass_block|minecraft:podzol,2,0,1#minecraft:fern,0.25,0.75,minecraft:grass_block|minecraft:podzol,0,0,1#minecraft:melon,0.02,0.1,minecraft:grass_block|minecraft:podzol,0,0,1#minecraft:short_grass,0.12,0.5,minecraft:grass_block|minecraft:podzol,0,0,1#minecraft:vine,0.12,0.4,minecraft:grass_block|minecraft:podzol,0,0,1;underhang=underhang(cave_vines_plant,2,12,24,cave_vines,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|create:limestone],minecraft:moss_block);hanging=;requirements=temperature=0.20..0.60,humidity>=0.20,weirdness>=0.15;priority=205;probability=1.00;terrain=rolling;structures=;modded=",
                            "biome=minecraft:flower_forest;surface=minecraft:grass_block;surfaceDetail=随机替换[minecraft:grass_block|minecraft:dandelion|minecraft:poppy|minecraft:blue_orchid|minecraft:allium|minecraft:azure_bluet|minecraft:red_tulip|minecraft:orange_tulip|minecraft:white_tulip|minecraft:pink_tulip|minecraft:oxeye_daisy|minecraft:cornflower|minecraft:lily_of_the_valley,minecraft:stone,0.60,2048];surfaceLayers=;subsurface=minecraft:stone;subsurfaceDetail=minecraft:diorite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=@minecraft:oak_checked,0.1,0.55,minecraft:grass_block,7,8,1#@minecraft:birch_checked,0.08,0.45,minecraft:grass_block,6,7,1#minecraft:dandelion,0.15,0.65,minecraft:grass_block,0,0,1#minecraft:poppy,0.14,0.6,minecraft:grass_block,0,0,1#minecraft:short_grass,0.2,0.65,minecraft:grass_block,0,0,1;underhang=underhang(cave_vines_plant,2,12,24,cave_vines,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|create:limestone],minecraft:moss_block);hanging=;requirements=temperature=0.05..0.40,humidity=0.10..0.40,weirdness>=0.15;priority=200;probability=1.00;terrain=hills;structures=;modded=",
                            "biome=minecraft:jagged_peaks;surface=minecraft:snow_block;surfaceDetail=表层[minecraft:snow_block,8,0.95];surfaceLayers=团块[minecraft:packed_ice,minecraft:stone,4,0.08];subsurface=minecraft:stone;subsurfaceDetail=minecraft:granite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=minecraft:snow,0.12,0.6,minecraft:snow_block,0,0,1;underhang=underhang(pointed_dripstone,4,24,16,pointed_dripstone,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|minecraft:tuff]);hanging=;requirements=temperature<=-0.05,erosion>=0.25,weirdness>=0.0;priority=198;probability=1.00;terrain=peaks;structures=;modded=",
                            "biome=minecraft:frozen_peaks;surface=minecraft:ice;surfaceDetail=表层[minecraft:packed_ice,8,0.50];surfaceLayers=团块[minecraft:ice,minecraft:stone,4,0.18];subsurface=minecraft:stone;subsurfaceDetail=minecraft:andesite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=minecraft:snow,0.08,0.45,minecraft:ice,0,0,1;underhang=underhang(pointed_dripstone,4,24,16,pointed_dripstone,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|minecraft:tuff]);hanging=;requirements=temperature<=-0.10,erosion>=0.25,weirdness<=0.0;priority=196;probability=1.00;terrain=peaks;structures=;modded=",
                            "biome=minecraft:stony_peaks;surface=minecraft:stone;surfaceDetail=表层[minecraft:cobblestone,5,0.45];surfaceLayers=团块[minecraft:diorite,minecraft:stone,8,0.12];subsurface=minecraft:stone;subsurfaceDetail=minecraft:diorite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.8;deep=minecraft:deepslate;deepDetail=minecraft:andesite;ores=default;liquidPools=;features=minecraft:stone_button,0.0,0.0,minecraft:stone,0,0,0;underhang=underhang(pointed_dripstone,4,24,16,pointed_dripstone,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|minecraft:tuff]);hanging=;requirements=temperature=-0.05..0.35,erosion>=0.25;priority=194;probability=1.00;terrain=peaks;structures=;modded=",
                            "biome=minecraft:snowy_slopes;surface=minecraft:snow_block;surfaceDetail=表层[minecraft:snow_block,5,0.90];surfaceLayers=团块[minecraft:granite,minecraft:stone,6,0.08];subsurface=minecraft:stone;subsurfaceDetail=minecraft:granite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=minecraft:snow,0.15,0.7,minecraft:snow_block,0,0,1;underhang=underhang(pointed_dripstone,4,24,16,pointed_dripstone,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|minecraft:tuff]);hanging=;requirements=temperature<=-0.10,erosion=0.00..0.25;priority=192;probability=1.00;terrain=mountains;structures=;modded=",
                            "biome=minecraft:grove;surface=minecraft:stone;surfaceDetail=随机替换[minecraft:grass_block|minecraft:moss_block,minecraft:stone,0.40,800];surfaceLayers=;subsurface=minecraft:stone;subsurfaceDetail=minecraft:diorite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=@minecraft:pine_checked,0.12,0.6,minecraft:grass_block,9,10,1#@minecraft:spruce_checked,0.08,0.55,minecraft:grass_block,9,10,1#minecraft:fern,0.2,0.6,minecraft:grass_block,0,0,1#minecraft:large_fern,0.1,0.4,minecraft:grass_block,2,0,1#minecraft:short_grass,0.2,0.55,minecraft:grass_block,0,0,1;underhang=underhang(cave_vines_plant,2,12,24,cave_vines,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|create:limestone],minecraft:moss_block);hanging=;requirements=temperature=-0.20..0.05,humidity>=-0.05,erosion<=0.00;priority=188;probability=1.00;terrain=mountains;structures=;modded=",
                            "biome=minecraft:windswept_gravelly_hills;surface=minecraft:gravel;surfaceDetail=随机替换[minecraft:gravel|minecraft:stone|minecraft:cobblestone,minecraft:stone,0.80,1800];surfaceLayers=巨石[minecraft:cobblestone,14,0.12];subsurface=minecraft:stone;subsurfaceDetail=minecraft:andesite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=@minecraft:oak_checked,0.05,0.35,minecraft:gravel,7,8,1;underhang=underhang(pointed_dripstone,4,24,16,pointed_dripstone,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|minecraft:tuff]);hanging=;requirements=erosion>=0.15,weirdness<=-0.15,temperature=-0.15..0.45;priority=186;probability=1.00;terrain=hills;structures=;modded=",
                            "biome=minecraft:windswept_hills;surface=minecraft:grass_block;surfaceDetail=随机替换[minecraft:grass_block|minecraft:gravel|minecraft:stone|minecraft:cobblestone,minecraft:stone,0.60,1600];surfaceLayers=巨石[minecraft:cobblestone,10,0.08];subsurface=minecraft:stone;subsurfaceDetail=minecraft:granite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.8;deep=minecraft:deepslate;deepDetail=minecraft:granite;ores=default;liquidPools=;features=@minecraft:oak_checked,0.07,0.4,minecraft:grass_block,7,8,1#@minecraft:spruce_checked,0.05,0.35,minecraft:grass_block,8,9,1#minecraft:short_grass,0.15,0.55,minecraft:grass_block,0,0,1;underhang=underhang(pointed_dripstone,4,24,16,pointed_dripstone,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|minecraft:tuff]);hanging=;requirements=erosion>=0.15,temperature=-0.10..0.45,weirdness=-0.15..0.15;priority=184;probability=1.00;terrain=hills;structures=;modded=",
                            "biome=minecraft:windswept_forest;surface=minecraft:grass_block;surfaceDetail=随机替换[minecraft:grass_block|minecraft:moss_block|minecraft:cobblestone,minecraft:stone,0.55,1600];surfaceLayers=巨石[minecraft:mossy_cobblestone,10,0.10];subsurface=minecraft:stone;subsurfaceDetail=minecraft:diorite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=@minecraft:oak_checked,0.12,0.55,minecraft:grass_block,7,9,1#@minecraft:dark_oak_checked,0.06,0.4,minecraft:grass_block,9,10,1#minecraft:short_grass,0.18,0.6,minecraft:grass_block,0,0,1#minecraft:fern,0.15,0.5,minecraft:grass_block,0,0,1;underhang=underhang(cave_vines_plant,2,12,24,cave_vines,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|create:limestone],minecraft:moss_block);hanging=;requirements=erosion>=0.08,temperature=0.05..0.40,weirdness>=0.15,humidity>=0.0;priority=182;probability=1.00;terrain=hills;structures=;modded=",
                            "biome=minecraft:jungle;surface=minecraft:grass_block;surfaceDetail=随机替换[minecraft:grass_block|minecraft:moss_block|minecraft:vine,minecraft:stone,0.55,1800];surfaceLayers=团块[minecraft:moss_block,minecraft:stone,8,0.12];subsurface=minecraft:stone;subsurfaceDetail=minecraft:granite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=@minecraft:jungle_tree_checked,0.2,0.75,minecraft:grass_block,9,11,2#@minecraft:fancy_oak_checked,0.06,0.45,minecraft:grass_block,9,10,1#minecraft:large_fern,0.2,0.7,minecraft:grass_block,2,0,1#minecraft:fern,0.25,0.75,minecraft:grass_block,0,0,1#minecraft:vine,0.18,0.65,minecraft:grass_block,0,0,1#minecraft:melon,0.03,0.12,minecraft:grass_block,0,0,1;underhang=underhang(cave_vines_plant,2,12,24,cave_vines,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|create:limestone],minecraft:moss_block);hanging=;requirements=temperature=0.20..0.70,humidity>=0.15;priority=183;probability=1.00;terrain=rolling;structures=;modded=",
                            "biome=minecraft:old_growth_birch_forest;surface=minecraft:grass_block;surfaceDetail=随机替换[minecraft:grass_block|minecraft:moss_block,minecraft:stone,0.50,1500];surfaceLayers=巨石[minecraft:mossy_cobblestone,9,0.12];subsurface=minecraft:stone;subsurfaceDetail=minecraft:diorite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=@minecraft:birch_checked,0.2,0.75,minecraft:grass_block,10,12,2#minecraft:fern,0.15,0.55,minecraft:grass_block,0,0,1#minecraft:short_grass,0.18,0.6,minecraft:grass_block,0,0,1;underhang=underhang(cave_vines_plant,2,12,24,cave_vines,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|create:limestone],minecraft:moss_block);hanging=;requirements=temperature=0.08..0.48,humidity=0.08..0.55,weirdness>=-0.15;priority=181;probability=1.00;terrain=hills;structures=;modded=",
                            "biome=minecraft:windswept_savanna;surface=minecraft:grass_block;surfaceDetail=随机替换[minecraft:grass_block|minecraft:stone|minecraft:cobblestone,minecraft:stone,0.55,1500];surfaceLayers=巨石[minecraft:cobblestone,8,0.08];subsurface=minecraft:stone;subsurfaceDetail=minecraft:granite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:granite;ores=default;liquidPools=;features=@minecraft:acacia_checked,0.06,0.4,minecraft:grass_block,9,10,1#minecraft:short_grass,0.15,0.5,minecraft:grass_block,0,0,1;underhang=underhang(vine,2,10,12,vine,[minecraft:sandstone|minecraft:smooth_sandstone|minecraft:stone]);hanging=;requirements=temperature>=0.30,humidity<=-0.10,erosion>=0.10;priority=180;probability=1.00;terrain=hills;structures=;modded=",
                            "biome=minecraft:desert;surface=minecraft:sand;surfaceDetail=表层[minecraft:sand,5,0.98];surfaceLayers=团块[minecraft:sandstone,minecraft:stone,8,0.30];subsurface=minecraft:stone;subsurfaceDetail=minecraft:granite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:granite;ores=default;liquidPools=;features=minecraft:cactus,0.12,0.55,minecraft:sand,0,0,1#minecraft:dead_bush,0.1,0.45,minecraft:sand,0,0,1#minecraft:sugar_cane,0.04,0.15,minecraft:sand,0,0,1;underhang=;hanging=;requirements=temperature>=0.25,humidity<=-0.10;priority=179;probability=1.00;terrain=flat;structures=;modded=",
                            "biome=minecraft:snowy_plains;surface=minecraft:snow_block;surfaceDetail=表层[minecraft:snow_block,4,0.98];surfaceLayers=;subsurface=minecraft:stone;subsurfaceDetail=minecraft:granite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=minecraft:snow,0.18,0.75,minecraft:snow_block,0,0,1#minecraft:ice,0.02,0.1,minecraft:snow_block,0,0,1;underhang=;hanging=;requirements=temperature<=-0.15,humidity=-0.35..0.10,erosion<=0.00;priority=178;probability=1.00;terrain=flat;structures=;modded=",
                            "biome=minecraft:snowy_taiga;surface=minecraft:snow_block;surfaceDetail=表层[minecraft:grass_block,2,0.25];surfaceLayers=团块[minecraft:podzol,minecraft:stone,3,0.15];subsurface=minecraft:stone;subsurfaceDetail=minecraft:diorite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=@minecraft:spruce_checked,0.14,0.6,minecraft:grass_block,9,10,1#minecraft:fern,0.12,0.45,minecraft:grass_block,0,0,1#minecraft:snow,0.12,0.6,minecraft:snow_block,0,0,1;underhang=underhang(pointed_dripstone,4,24,16,pointed_dripstone,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|minecraft:tuff]);hanging=;requirements=temperature<=-0.05,humidity>=0.0;priority=176;probability=1.00;terrain=hills;structures=;modded=",
                            "biome=minecraft:birch_forest;surface=minecraft:grass_block;surfaceDetail=;surfaceLayers=;subsurface=minecraft:stone;subsurfaceDetail=minecraft:diorite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=@minecraft:birch_checked,0.18,0.7,minecraft:grass_block,7,8,2#minecraft:short_grass,0.2,0.6,minecraft:grass_block,0,0,1#minecraft:fern,0.14,0.5,minecraft:grass_block,0,0,1;underhang=underhang(cave_vines_plant,2,12,24,cave_vines,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|create:limestone],minecraft:moss_block);hanging=;requirements=temperature=0.05..0.50,humidity=-0.05..0.45,weirdness<=-0.15;priority=177;probability=1.00;terrain=hills;structures=;modded=",
                            "biome=minecraft:taiga;surface=minecraft:grass_block;surfaceDetail=随机替换[minecraft:grass_block|minecraft:podzol,minecraft:stone,0.40,1200];surfaceLayers=;subsurface=minecraft:stone;subsurfaceDetail=minecraft:diorite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=@minecraft:spruce_checked,0.14,0.6,minecraft:grass_block,8,9,1#minecraft:fern,0.16,0.6,minecraft:grass_block,0,0,1#minecraft:large_fern,0.06,0.3,minecraft:grass_block,2,0,1#minecraft:short_grass,0.15,0.5,minecraft:grass_block,0,0,1#minecraft:sweet_berry_bush,0.03,0.15,minecraft:grass_block,0,0,1;underhang=underhang(cave_vines_plant,2,12,24,cave_vines,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|create:limestone],minecraft:moss_block);hanging=;requirements=temperature=-0.05..0.20,humidity=-0.05..0.20;priority=168;probability=1.00;terrain=hills;structures=;modded=",
                            "biome=minecraft:old_growth_pine_taiga;surface=minecraft:podzol;surfaceDetail=随机替换[minecraft:podzol|minecraft:grass_block,minecraft:stone,0.75,1800];surfaceLayers=巨石[minecraft:mossy_cobblestone,10,0.14];subsurface=minecraft:stone;subsurfaceDetail=minecraft:diorite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=@minecraft:pine_checked,0.18,0.7,minecraft:podzol,11,13,2#minecraft:large_fern,0.18,0.65,minecraft:podzol,2,0,1#minecraft:fern,0.22,0.7,minecraft:podzol,0,0,1#minecraft:moss_carpet,0.12,0.45,minecraft:podzol,0,0,1;underhang=underhang(cave_vines_plant,2,12,24,cave_vines,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|create:limestone],minecraft:moss_block);hanging=;requirements=temperature=-0.05..0.20,humidity>=0.15,weirdness>=0.10;priority=172;probability=1.00;terrain=hills;structures=;modded=",
                            "biome=minecraft:old_growth_spruce_taiga;surface=minecraft:podzol;surfaceDetail=随机替换[minecraft:podzol|minecraft:moss_block,minecraft:stone,0.75,1800];surfaceLayers=巨石[minecraft:mossy_cobblestone,12,0.18];subsurface=minecraft:stone;subsurfaceDetail=minecraft:andesite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=@minecraft:spruce_checked,0.18,0.7,minecraft:podzol,11,13,2#minecraft:large_fern,0.16,0.65,minecraft:podzol,2,0,1#minecraft:fern,0.2,0.7,minecraft:podzol,0,0,1#minecraft:moss_carpet,0.14,0.55,minecraft:podzol,0,0,1;underhang=underhang(cave_vines_plant,2,12,24,cave_vines,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|create:limestone],minecraft:moss_block);hanging=;requirements=temperature=-0.04..0.19,humidity=-0.61..0.24,weirdness=-0.10..0.15,erosion=-0.28..0.10;priority=170;probability=1.00;terrain=hills;structures=;modded=",
                            "biome=minecraft:meadow;surface=minecraft:grass_block;surfaceDetail=随机替换[minecraft:grass_block|minecraft:azure_bluet|minecraft:cornflower|minecraft:dandelion|minecraft:poppy|minecraft:allium|minecraft:oxeye_daisy|minecraft:daisy,minecraft:stone,0.60,2048];surfaceLayers=;subsurface=minecraft:stone;subsurfaceDetail=minecraft:diorite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=@minecraft:oak_checked,0.05,0.3,minecraft:grass_block,7,8,1#minecraft:azure_bluet,0.16,0.65,minecraft:grass_block,0,0,1#minecraft:cornflower,0.12,0.55,minecraft:grass_block,0,0,1#minecraft:short_grass,0.25,0.7,minecraft:grass_block,0,0,1;underhang=underhang(cave_vines_plant,2,12,24,cave_vines,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|create:limestone],minecraft:moss_block);hanging=;requirements=humidity>=0.0,erosion<=0.10,temperature=-0.05..0.35;priority=166;probability=1.00;terrain=rolling;structures=;modded=",
                            "biome=minecraft:dark_forest;surface=minecraft:grass_block;surfaceDetail=随机替换[minecraft:grass_block|minecraft:moss_block,minecraft:stone,0.55,1500];surfaceLayers=巨石[minecraft:mossy_cobblestone,10,0.15];subsurface=minecraft:stone;subsurfaceDetail=minecraft:diorite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=@minecraft:dark_oak_checked,0.22,0.75,minecraft:grass_block,9,10,2#@minecraft:oak_checked,0.1,0.5,minecraft:grass_block,7,8,1#@minecraft:brown_mushroom_checked,0.06,0.35,minecraft:grass_block,8,6,1#@minecraft:red_mushroom_checked,0.05,0.3,minecraft:grass_block,7,6,1#minecraft:short_grass,0.15,0.55,minecraft:grass_block,0,0,1;underhang=underhang(cave_vines_plant,2,12,24,cave_vines,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|create:limestone],minecraft:moss_block);hanging=;requirements=temperature=-0.04..0.05,humidity=-0.49..-0.20,weirdness=-0.66..-0.08,erosion=-0.35..0.00;priority=162;probability=1.00;terrain=rolling;structures=;modded=",
                            "biome=minecraft:savanna_plateau;surface=minecraft:grass_block;surfaceDetail=表层[minecraft:coarse_dirt,3,0.25];surfaceLayers=;subsurface=minecraft:stone;subsurfaceDetail=minecraft:granite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:granite;ores=default;liquidPools=;features=@minecraft:acacia_checked,0.04,0.3,minecraft:grass_block,9,10,1#minecraft:short_grass,0.12,0.5,minecraft:grass_block,0,0,1;underhang=underhang(vine,2,10,12,vine,[minecraft:sandstone|minecraft:smooth_sandstone|minecraft:stone]);hanging=;requirements=temperature=0.16..0.54,humidity=-0.19..0.22,weirdness=-0.40..0.16,erosion=-0.15..0.05;priority=158;probability=1.00;terrain=mesa;structures=;modded=",
                            "biome=minecraft:wooded_badlands;surface=minecraft:grass_block;surfaceDetail=表层[minecraft:coarse_dirt,2,0.25];surfaceLayers=团块[minecraft:red_sand,minecraft:stone,2,0.12];subsurface=minecraft:stone;subsurfaceDetail=minecraft:terracotta;badlandsDetail=minecraft:terracotta,40,0.58,[minecraft:orange_terracotta;minecraft:yellow_terracotta;minecraft:white_terracotta;minecraft:light_gray_terracotta;minecraft:brown_terracotta;minecraft:red_terracotta];deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:granite;ores=default;liquidPools=;features=@minecraft:oak_checked,0.07,0.4,minecraft:grass_block,7,8,1#minecraft:dead_bush,0.1,0.45,minecraft:grass_block,0,0,1;underhang=underhang(vine,2,10,12,vine,[minecraft:sandstone|minecraft:smooth_sandstone|minecraft:stone]);hanging=;requirements=temperature=0.20..0.55,humidity<=-0.10,erosion<=0.05,weirdness<=-0.05;priority=156;probability=1.00;terrain=hills;structures=;modded=",
                            "biome=minecraft:badlands;surface=minecraft:red_sand;surfaceDetail=表层[minecraft:terracotta,5,0.65];surfaceLayers=团块[minecraft:red_sand,minecraft:stone,2,0.12];subsurface=minecraft:stone;subsurfaceDetail=minecraft:terracotta;badlandsDetail=minecraft:terracotta,48,0.58,[minecraft:orange_terracotta;minecraft:yellow_terracotta;minecraft:white_terracotta;minecraft:light_gray_terracotta;minecraft:brown_terracotta;minecraft:red_terracotta];deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:granite;ores=default;liquidPools=;features=minecraft:dead_bush,0.1,0.45,minecraft:red_sand,0,0,1#minecraft:cactus,0.06,0.3,minecraft:red_sand,0,0,1;underhang=underhang(vine,2,10,12,vine,[minecraft:sandstone|minecraft:smooth_sandstone|minecraft:stone]);hanging=;requirements=temperature>=0.20,humidity<=-0.10,weirdness<=0.0,erosion=0.00..0.25;priority=152;probability=1.00;terrain=hills;structures=;modded=",
                            "biome=minecraft:forest;surface=minecraft:grass_block;surfaceDetail=;surfaceLayers=团块[minecraft:moss_block,minecraft:stone,6,0.10];subsurface=minecraft:stone;subsurfaceDetail=minecraft:diorite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=@minecraft:oak_checked,0.14,0.6,minecraft:grass_block,7,8,1#@minecraft:birch_checked,0.09,0.45,minecraft:grass_block,6,7,1#minecraft:short_grass,0.18,0.6,minecraft:grass_block,0,0,1#minecraft:fern,0.12,0.45,minecraft:grass_block,0,0,1;underhang=underhang(cave_vines_plant,2,12,24,cave_vines,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|create:limestone],minecraft:moss_block);hanging=;requirements=temperature=0.05..0.40,humidity=-0.05..0.15,erosion<=0.10;priority=150;probability=1.00;terrain=hills;structures=;modded=",
                            "biome=minecraft:savanna;surface=minecraft:grass_block;surfaceDetail=表层[minecraft:coarse_dirt,2,0.22];surfaceLayers=;subsurface=minecraft:stone;subsurfaceDetail=minecraft:granite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:granite;ores=default;liquidPools=;features=@minecraft:acacia_checked,0.05,0.35,minecraft:grass_block,9,10,1#minecraft:short_grass,0.2,0.65,minecraft:grass_block,0,0,1;underhang=underhang(vine,2,10,12,vine,[minecraft:sandstone|minecraft:smooth_sandstone|minecraft:stone]);hanging=;requirements=temperature=0.05..0.45,humidity=-0.15..0.10,weirdness=0.35..0.75,erosion=-0.20..0.10;priority=146;probability=1.00;terrain=flat;structures=;modded=",
                            "biome=minecraft:sparse_jungle;surface=minecraft:grass_block;surfaceDetail=随机替换[minecraft:grass_block|minecraft:moss_block,minecraft:stone,0.45,1200];surfaceLayers=;subsurface=minecraft:stone;subsurfaceDetail=minecraft:granite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=@minecraft:jungle_tree_checked,0.1,0.5,minecraft:grass_block,8,10,1#minecraft:large_fern,0.1,0.5,minecraft:grass_block,2,0,1#minecraft:fern,0.18,0.6,minecraft:grass_block,0,0,1#minecraft:short_grass,0.15,0.55,minecraft:grass_block,0,0,1;underhang=underhang(cave_vines_plant,2,12,24,cave_vines,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|create:limestone],minecraft:moss_block);hanging=;requirements=temperature=0.20..0.55,humidity=0.05..0.25,erosion>=0.00;priority=142;probability=1.00;terrain=rolling;structures=;modded=",
                            "biome=minecraft:sunflower_plains;surface=minecraft:grass_block;surfaceDetail=随机替换[minecraft:grass_block|minecraft:sunflower,minecraft:stone,0.55,2048];surfaceLayers=;subsurface=minecraft:stone;subsurfaceDetail=minecraft:diorite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=minecraft:sunflower,0.15,0.65,minecraft:grass_block,0,0,1#@minecraft:oak_checked,0.04,0.25,minecraft:grass_block,6,7,1#minecraft:dandelion,0.15,0.6,minecraft:grass_block,0,0,1#minecraft:poppy,0.14,0.55,minecraft:grass_block,0,0,1#minecraft:short_grass,0.25,0.7,minecraft:grass_block,0,0,1;underhang=underhang(cave_vines_plant,2,12,24,cave_vines,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|create:limestone],minecraft:moss_block);hanging=;requirements=temperature=0.10..0.45,humidity<=-0.05,weirdness>=0.10;priority=130;probability=1.00;terrain=flat;structures=;modded=",
                            "biome=minecraft:plains;surface=minecraft:grass_block;surfaceDetail=随机替换[minecraft:grass_block|minecraft:dandelion|minecraft:poppy|minecraft:azure_bluet|minecraft:cornflower|minecraft:oxeye_daisy,minecraft:stone,0.50,1800];surfaceLayers=;subsurface=minecraft:stone;subsurfaceDetail=minecraft:diorite;badlandsDetail=;deepEnabled=true;deepLayerLine=0.5;deep=minecraft:deepslate;deepDetail=minecraft:tuff;ores=default;liquidPools=;features=@minecraft:oak_checked,0.03,0.18,minecraft:grass_block,6,7,1#minecraft:dandelion,0.16,0.65,minecraft:grass_block,0,0,1#minecraft:poppy,0.15,0.6,minecraft:grass_block,0,0,1#minecraft:short_grass,0.22,0.7,minecraft:grass_block,0,0,1;underhang=underhang(cave_vines_plant,2,12,24,cave_vines,[minecraft:stone|minecraft:diorite|minecraft:deepslate|minecraft:andesite|minecraft:granite|create:limestone],minecraft:moss_block);hanging=;requirements=temperature=0.05..0.40,humidity<=-0.05,erosion<=0.05,weirdness=-0.10..0.10;priority=128;probability=1.00;terrain=flat;structures=;modded="
                    ),
                    entry -> entry instanceof String
            );

    public static final ModConfigSpec.IntValue ORE_ISLAND_SPACING =
            BUILDER.defineInRange("oreIslands.spacing", 1000, 64, 100000);
    public static final ModConfigSpec.IntValue ORE_ISLAND_MIN_RADIUS =
            BUILDER.defineInRange("oreIslands.minRadius", 8, 1, 64);
    public static final ModConfigSpec.IntValue ORE_ISLAND_MAX_RADIUS =
            BUILDER.defineInRange("oreIslands.maxRadius", 16, 1, 64);
    public static final ModConfigSpec.IntValue ORE_ISLAND_CENTER_Y =
            BUILDER.defineInRange("oreIslands.centerY", -55, -64, -1);
    public static final ModConfigSpec.IntValue ORE_ISLAND_PASSES =
            BUILDER.defineInRange("oreIslands.passes", 5, 1, 16);
    public static final ModConfigSpec.DoubleValue ORE_ISLAND_ORE_CHANCE =
            BUILDER.defineInRange("oreIslands.oreChance", 0.45D, 0.0D, 1.0D);
    public static final ModConfigSpec.IntValue ORE_ISLAND_HEIGHT_JITTER =
            BUILDER.defineInRange("oreIslands.heightJitter", 24, 0, 128);

    public static final ModConfigSpec.IntValue DEBRIS_LARGE_ISLAND_RADIUS =
            BUILDER.defineInRange("debris.largeIslandRadius", 700, 64, 100000);
    public static final ModConfigSpec.IntValue DEBRIS_MIN_COUNT =
            BUILDER.defineInRange("debris.minCount", 3, 0, 32);
    public static final ModConfigSpec.IntValue DEBRIS_MAX_COUNT =
            BUILDER.defineInRange("debris.maxCount", 7, 0, 64);
    public static final ModConfigSpec.IntValue DEBRIS_MAX_RADIUS =
            BUILDER.defineInRange("debris.maxRadius", 6, 1, 32);
    public static final ModConfigSpec.DoubleValue DEBRIS_ORE_CHANCE =
            BUILDER.defineInRange("debris.oreChance", 0.14D, 0.0D, 1.0D);

    public static final ModConfigSpec.BooleanValue STRONGHOLD_WRAP_ISLAND =
            BUILDER.define("stronghold.wrapIsland", true);
    public static final ModConfigSpec.IntValue STRONGHOLD_WRAP_PADDING =
            BUILDER.defineInRange("stronghold.wrapPadding", 16, 0, 256);
    public static final ModConfigSpec.BooleanValue STRONGHOLD_DELETE_IF_NOT_ON_ISLAND =
            BUILDER.define("stronghold.deleteIfNotOnIsland", false);
    public static final ModConfigSpec.IntValue STRONGHOLD_MOSS_SEEDS =
            BUILDER.defineInRange("stronghold.mossSeeds", 6, 0, 256);
    public static final ModConfigSpec.IntValue STRONGHOLD_MOSS_SPREAD_STEPS =
            BUILDER.defineInRange("stronghold.mossSpreadSteps", 200, 0, 100000);
    public static final ModConfigSpec.DoubleValue STRONGHOLD_MOSS_SPREAD_CHANCE =
            BUILDER.defineInRange("stronghold.mossSpreadChance", 0.6D, 0.0D, 1.0D);

    public static final ModConfigSpec SPEC = BUILDER.build();

    private SkylandsConfig() {}
}
